name: "Render Documentation"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build_docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install requirements
      run: |
          python -m pip install --upgrade pip
          pip install PySide6
          pip install -v ".[docs]"
    - name: Build docs
      run: |
          cd ./docs
          python -c "import mne_pipeline_hd; print(dir(mne_pipeline_hd.gui))"
          make html
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: html-docs
        path: docs/build/html/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/html
